version: '3.3'
services:
  flask:
    build: backend/
    volumes:
        - ./backend:/app
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
        - 5000:5000
    command: flask run --host 0.0.0.0 --port 5000
    # entrypoint:
    #   - flask
    #   - run
    #   - --host=0.0.0.0
    networks: 
        - default

